[package]
name = "muon-reactivity"
version = "0.1.0"
edition = "2024"

[dependencies]
muon = { version = "0.20.1", path = "../muon" }
muon-reactivity-derive = { version = "0.1.0", path = "../muon-reactivity-derive" }
muon-store = { version = "0.1.0", path = "../muon-store" }
reactive_graph = { version = "0.2.14", features = ["effects"] }
rustc-hash = "2.1.3"

[dev-dependencies]
any_spawner = { version = "0.3.0", features = ["futures-executor", "tokio"] }
serde = { workspace = true, features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "sync"] }
