//! Core store: an atomically-published value with a tracked write path.
//!
//! The value lives in a `RwLock<Arc<T>>`. Writers take the write lock and
//! mutate in place via `Arc::make_mut` (zero-copy when no reader holds the
//! `Arc`, copy-on-write otherwise); readers take a short read lock and
//! clone the `Arc` (O(1)), then read lock-free.
//!
//! The store does not own any consumers. Every write entry point produces
//! a [`ChangeEvent`] (which paths changed, plus the mutation tree when a
//! consumer asked for it); notification is the caller's concern (see
//! `ReactiveStore::notify` in the reactivity layer).

use crate::path::StorePath;
use muon::observe::{Flush, ObserveExt, ObserveSink};
use muon::Observe;
use or_poisoned::OrPoisoned;
use std::marker::PhantomData;
use std::sync::{Arc, RwLock};

/// A model type that can be written through `track!`.
///
/// Generated by `#[derive(Track)]`. The marker is the capability gate for
/// the tracked write path: `write_tracked` and the `Write` typestate
/// require `T: Track` (which implies `Observe + Clone`).
pub trait Track: Observe + Clone + 'static {}

/// Collection-form support: an observed map is a writable model.
///
/// Enabled by the `indexmap` feature. muon observes `IndexMap<K, V>` as a
/// map whose keys become path segments, so `track!` bodies can call
/// `insert` / `remove` / `get_mut` and the keyed mutations flow through
/// the sync pipeline unchanged.
#[cfg(feature = "indexmap")]
impl<K, V> Track for indexmap::IndexMap<K, V>
where
    K: serde::Serialize + Clone + std::hash::Hash + Eq + 'static,
    V: Observe + Clone + Sized + muon::general::SerializeSnapshot + 'static,
{
}

/// A field-level change produced by a write.
///
/// This is the common output of every write entry point. Consumers take
/// what they need:
///
/// - `paths` — which paths changed. The reactivity layer notifies the
///   corresponding triggers from this list.
#[derive(Debug, Default, Clone)]
pub struct ChangeEvent {
    /// Changed paths (root-to-leaf order).
    pub paths: Vec<StorePath>,
}

/// The result of a write: the body's return value plus the change event.
///
/// Produced by every write entry point ([`Write::commit`],
/// [`ObservedWrite::flush`], [`Store::write`]). The model
/// type `T` is carried so that consuming consumers (e.g. the reactivity
/// layer's `CommitNotify`) can bind the event to a specific store model.
/// Consume it with [`result`](Self::result) (the body's return value),
/// [`event`](Self::event) (the change event, e.g. for sync consumers), or
/// [`into_parts`](Self::into_parts). Dropping it is harmless — the write
/// already happened.
pub struct CommitResult<T, R> {
    result: R,
    event: ChangeEvent,
    _marker: PhantomData<fn() -> T>,
}

impl<T, R> CommitResult<T, R> {
    /// The mutation body's return value.
    pub fn result(self) -> R {
        self.result
    }

    /// The change event produced by the write.
    pub fn event(self) -> ChangeEvent {
        self.event
    }

    /// Split into the body's return value and the change event.
    pub fn into_parts(self) -> (R, ChangeEvent) {
        (self.result, self.event)
    }
}

/// A store that holds one coherent value and publishes it atomically.
///
/// # Notification contract
///
/// Notifications are invalidations, not commit events. A notification
/// means "the value you read may be stale, re-read it". It carries no
/// payload, and it does not compare values: a no-op commit still reruns
/// subscribers.
///
/// Publication and notification are separate moments. A write publishes
/// the new value, releases the store lock, then notifies. A plain reader
/// can observe the new value before subscribers rerun. Subscribers always
/// re-read through `Field::get`, so they never miss the latest value.
///
/// The store itself never notifies: it has no consumer to notify. Wrap it
/// in the reactivity layer's `ReactiveStore` (with
/// `#[derive(Reactivity)]`) to attach triggers and notify — *after* the
/// write lock is released, so an effect may write back from its rerun
/// without deadlocking.
pub struct Store<T: 'static> {
    pub(crate) inner: Arc<StoreInner<T>>,
}

pub(crate) struct StoreInner<T: 'static> {
    pub(crate) value: RwLock<Arc<T>>,
}

impl<T: 'static> Store<T> {
    /// Create a store holding `value`.
    ///
    /// No triggers are registered — this is the plain data layer. Use
    /// `ReactiveStore::new` when you need reactive subscription.
    pub fn new(value: T) -> Self {
        Self {
            inner: Arc::new(StoreInner {
                value: RwLock::new(Arc::new(value)),
            }),
        }
    }

    /// Read the current value as one consistent snapshot.
    ///
    /// Takes a short read lock, clones the `Arc` (O(1)), and releases the
    /// lock. The returned `Arc<T>` pins one version: every field read
    /// through it comes from the same version, lock-free.
    ///
    /// Use `Field::get` or `Field::with` for a single tracked read. They
    /// declare a reactive dependency; this method declares none.
    pub fn snapshot(&self) -> Arc<T> {
        self.inner.value.read().or_poisoned().clone()
    }

    /// Raw write: take the write lock and run `f` on the current `Arc`.
    ///
    /// `f` may replace the value entirely (`*arc = Arc::new(v)`) or mutate
    /// it in place via [`Arc::make_mut`]. The produced [`ChangeEvent`]
    /// reports a root-level change (broadcast), because the raw entry
    /// point cannot know which fields changed.
    ///
    /// Notification is the caller's job: the reactivity layer's
    /// `CommitNotify` runs after this returns, never inside `f` (the lock
    /// is held there).
    pub fn write<R>(&self, f: impl FnOnce(&mut Arc<T>) -> R) -> CommitResult<T, R> {
        let mut guard = self.inner.value.write().or_poisoned();
        let result = f(&mut guard);
        drop(guard);
        CommitResult {
            result,
            event: ChangeEvent {
                paths: vec![StorePath::new()],
            },
            _marker: PhantomData,
        }
    }

    /// Start a tracked write, baking the mutation body into a [`Write`].
    ///
    /// This is the expansion target of `track!`. The body is stored inline
    /// (no boxing, no dynamic dispatch). Consume the [`Write`] with
    /// [`observe`](Write::observe) or [`commit`](Write::commit).
    #[doc(hidden)]
    pub fn write_tracked<R>(
        &self,
        body: impl for<'ob> FnOnce(&mut <T as Observe>::Observer<'ob, T, muon::helper::Zero>) -> R,
    ) -> Write<
        '_,
        T,
        impl for<'ob> FnOnce(&mut <T as Observe>::Observer<'ob, T, muon::helper::Zero>) -> R,
    >
    where
        T: Track,
    {
        Write { store: self, body }
    }
}

// ── Clone ──────────────────────────────────────────────────────────────

impl<T: 'static> Clone for Store<T> {
    fn clone(&self) -> Self {
        Self {
            inner: Arc::clone(&self.inner),
        }
    }
}

// ── Tracked write flow (typestate) ─────────────────────────────────────

/// Entry point of a tracked write.
///
/// A tracked write intent: the mutation body captured by [`track!`](crate::track),
/// not yet executed and not holding any lock.
///
/// Consume it with [`observe`](Write::observe) to take the write lock, or
/// [`commit`](Write::commit) to run the default local write pipeline.
#[must_use = "the write does not run until commit() or observe() is called"]
pub struct Write<'a, T: 'static, B> {
    store: &'a Store<T>,
    body: B,
}

impl<'a, T, B> Write<'a, T, B> {
    /// The store this write targets.
    ///
    /// The write is lazy — the store is unmodified and unlocked here.
    /// Snapshot through this handle to capture the pre-write value (a
    /// sync consumer's `original`) before observing.
    pub fn store(&self) -> &'a Store<T> {
        self.store
    }

    /// Take the write lock. The mutation body does not run yet — it runs
    /// on [`flush`](ObservedWrite::flush).
    ///
    /// Dropping the returned [`ObservedWrite`] without flushing aborts the
    /// write: the body never ran and the value is untouched.
    pub fn observe(self) -> ObservedWrite<'a, T, B>
    where
        T: Track,
    {
        let lock = self.store.inner.value.write().or_poisoned();
        ObservedWrite {
            lock,
            body: self.body,
        }
    }

    /// Run the default local write pipeline: observe, flush.
    ///
    /// Equivalent to `self.observe().flush()`. Returns the body's result
    /// and the produced change event. The store itself does not notify;
    /// the caller decides (see `CommitResult` consumption).
    pub fn commit<R>(self) -> CommitResult<T, R>
    where
        B: for<'ob> FnOnce(&mut <T as Observe>::Observer<'ob, T, muon::helper::Zero>) -> R,
        for<'ob> <T as Observe>::Observer<'ob, T, muon::helper::Zero>: Flush<ObserveSink>,
        T: Track,
    {
        self.observe().flush()
    }
}

/// A locked view of the store's current value.
///
/// Holds the write lock until consumed by [`flush`](ObservedWrite::flush).
/// Dropping it without flushing aborts the write: the body never ran and
/// the value is untouched.
#[must_use = "dropping the observed write aborts it; call flush"]
pub struct ObservedWrite<'a, T: 'static, B> {
    lock: std::sync::RwLockWriteGuard<'a, Arc<T>>,
    body: B,
}

impl<'a, T: 'static + Track, B> ObservedWrite<'a, T, B> {
    /// Run the mutation body, release the lock, return the result and the
    /// change event.
    pub fn flush<R>(self) -> CommitResult<T, R>
    where
        B: for<'ob> FnOnce(&mut <T as Observe>::Observer<'ob, T, muon::helper::Zero>) -> R,
        for<'ob> <T as Observe>::Observer<'ob, T, muon::helper::Zero>: Flush<ObserveSink>,
    {
        let (lock, result, paths) = self.run_body();
        drop(lock); // publish: release the write lock
        CommitResult {
            result,
            event: ChangeEvent { paths },
            _marker: PhantomData,
        }
    }

    /// Run the mutation body under the write lock and hand the sink's
    /// collected output to the converter.
    ///
    /// This is the sync write entry: the converter builds transactions
    /// (and enqueues them) while the write lock is still held, so the
    /// queue insertion and the store publication stay atomic. The sink
    /// type is chosen by the caller (for example, `SyncSink` in the sync
    /// layer); the converter also receives the body's result.
    ///
    /// # Atomicity
    ///
    /// The store is rolled back unless the converter returns `Ok`: the
    /// pre-mutation value is restored when the write lock is released,
    /// so a failed enqueue never publishes a mutated store. A panic in
    /// the body or the converter rolls back the same way (the guard's
    /// `Drop` restores `base` during unwinding).
    pub fn sync_flush<Sk: muon::observe::Sink, R, S, E>(
        self,
        sink: Sk,
        convert: impl FnOnce(Sk, R) -> Result<S, E>,
    ) -> Result<S, E>
    where
        B: for<'ob> FnOnce(&mut <T as Observe>::Observer<'ob, T, muon::helper::Zero>) -> R,
        for<'ob> <T as Observe>::Observer<'ob, T, muon::helper::Zero>: Flush<Sk>,
    {
        let base = self.lock.clone();
        let body = self.body;
        let mut rollback = RollbackGuard {
            lock: Some(self.lock),
            base,
        };
        let t = Arc::make_mut(rollback.lock.as_mut().expect("write lock held"));
        let mut observer = ObserveExt::__observe(t);
        let result = body(&mut observer);
        let mut sink = sink;
        Flush::flush(&mut observer, &mut sink);
        drop(observer);
        let out = convert(sink, result);
        if out.is_ok() {
            // Commit: release the write lock, publishing the new value.
            rollback.lock = None;
        }
        out
    }

    /// Shared body of the local write.
    ///
    /// Takes the write lock's `Arc`, gets a `&mut T` via `Arc::make_mut`
    /// (zero-copy when no reader holds the `Arc`), runs the observer,
    /// flushes the change stream, and extracts notification paths.
    /// Returns the still-held write lock, the body's result, and the
    /// paths — the caller decides the publication point.
    fn run_body<R>(mut self) -> (std::sync::RwLockWriteGuard<'a, Arc<T>>, R, Vec<StorePath>)
    where
        B: for<'ob> FnOnce(&mut <T as Observe>::Observer<'ob, T, muon::helper::Zero>) -> R,
        for<'ob> <T as Observe>::Observer<'ob, T, muon::helper::Zero>: Flush<ObserveSink>,
    {
        let t = Arc::make_mut(&mut *self.lock);
        let mut observer = ObserveExt::__observe(t);
        let result = (self.body)(&mut observer);
        let mut sink = muon::observe::ObserveSink::new();
        Flush::flush(&mut observer, &mut sink);
        drop(observer);
        let changes = sink.into_changes();
        let paths = changes.into_iter().map(|change| change.path).collect();
        (self.lock, result, paths)
    }
}

/// Restores the pre-mutation value on drop unless disarmed.
///
/// The sync write's rollback mechanism: the body may mutate the store
/// in place; only a successful (disarmed) convert publishes it. A
/// failed convert or a panic (the guard drops during unwinding)
/// restores `base` when the write lock is released.
struct RollbackGuard<'a, T: 'static> {
    lock: Option<std::sync::RwLockWriteGuard<'a, Arc<T>>>,
    base: Arc<T>,
}

impl<'a, T: 'static> Drop for RollbackGuard<'a, T> {
    fn drop(&mut self) {
        // Abort: restore the pre-mutation value. `Ok` disarms by
        // taking the lock out; a failed convert or a panic runs this
        // with the lock still held. Cloning the `Arc` does not
        // allocate, so this cannot panic during unwinding.
        if let Some(mut lock) = self.lock.take() {
            *lock = self.base.clone();
        }
    }
}
