use crate::path::TriggerMap;
use muon::Observe;
use muon_store::{Store, StorePath};
use reactive_graph::signal::ArcTrigger;
use reactive_graph::traits::Track;
use std::marker::PhantomData;
use std::sync::{Arc, OnceLock};

#[derive(Default)]
pub(crate) struct TriggerCache {
    triggers: OnceLock<Vec<ArcTrigger>>,
}

pub struct Field<T: 'static, S: 'static> {
    pub(crate) path: StorePath,
    pub(crate) offset: usize,
    pub(crate) store: Store<T>,
    pub(crate) triggers: Arc<TriggerMap>,
    pub(crate) trigger_cache: Arc<TriggerCache>,
    _phantom: PhantomData<S>,
}

impl<T: Observe + Clone + 'static, S: Clone + 'static> Field<T, S> {
    /// Creates a field accessor.
    ///
    /// This constructor is generated by the `Reactivity` derive. Do not
    /// call it directly.
    ///
    /// # Safety
    ///
    /// - `offset` must be the byte offset of a field of type `S` inside
    ///   `T`, as produced by [`core::mem::offset_of!`]. Any other value
    ///   makes `Field::get_untracked` and `Field::with_untracked` read
    ///   outside the value or with the wrong type, which is undefined
    ///   behavior.
    /// - `T` must not be `#[repr(packed)]`. A packed layout does not
    ///   guarantee the alignment that `S` requires, so forming a `&S`
    ///   from the offset is undefined behavior.
    #[doc(hidden)]
    pub unsafe fn new(
        path: StorePath,
        offset: usize,
        store: Store<T>,
        triggers: Arc<TriggerMap>,
    ) -> Self {
        Self {
            path,
            offset,
            store,
            triggers,
            trigger_cache: Arc::new(TriggerCache::default()),
            _phantom: PhantomData,
        }
    }

    /// Returns the store path of this field.
    ///
    /// The path locates this field inside the store value. For example,
    /// the `name` accessor of `ReactiveStore<AppState>` has path `["name"]`.
    pub fn path(&self) -> &StorePath {
        &self.path
    }

    /// Reads the current value and subscribes to this field.
    ///
    /// The subscription registers the current reactive scope with this
    /// field's path, so the scope reruns when the field changes. Use
    /// [`get_untracked`](Self::get_untracked) to read without subscribing.
    pub fn get(&self) -> S {
        self.track();
        self.get_untracked()
    }

    /// Reads the current value without subscribing.
    ///
    /// Snapshot reads the value through the public store API (short read
    /// lock + `Arc` clone, O(1)), then clones the value out of the pinned
    /// `Arc` via the offset. This is the raw snapshot read: it never
    /// registers a subscriber, so a call inside an effect does not create
    /// a dependency on this field.
    pub fn get_untracked(&self) -> S {
        let arc = self.store.snapshot();
        let base = Arc::as_ptr(&arc) as *const u8;
        // SAFETY: `arc` keeps the `Arc<T>` allocation alive for the whole
        // call; `Arc::as_ptr` points at the `T` itself. The offset comes
        // from `offset_of!` (generated `Field::new`), so the add stays
        // inside the allocation, aligned for `S`. The clone completes
        // before `arc` drops.
        unsafe { (*(base.add(self.offset) as *const S)).clone() }
    }

    /// Reads the current value through a closure and subscribes to this
    /// field.
    ///
    /// Unlike [`get`](Self::get), the value is not cloned: `f` receives a
    /// reference that is valid for the duration of the call. The closure
    /// runs synchronously while the store's read lock is held.
    pub fn with<R>(&self, f: impl FnOnce(&S) -> R) -> R {
        self.track();
        self.with_untracked(f)
    }

    /// Reads the current value through a closure without subscribing.
    ///
    /// `f` receives a reference that is valid for the duration of the
    /// call. The value is pinned by a snapshot `Arc` (short read lock +
    /// clone), so the closure runs without holding any store lock.
    pub fn with_untracked<R>(&self, f: impl FnOnce(&S) -> R) -> R {
        let arc = self.store.snapshot();
        let base = Arc::as_ptr(&arc) as *const u8;
        // SAFETY: `arc` pins the value for the closure's duration; the
        // derived offset keeps the pointer inside the allocation, aligned
        // for `S`. `f` runs synchronously, so the reference cannot outlive
        // the arc.
        f(unsafe { &*(base.add(self.offset) as *const S) })
    }

    fn track(&self) {
        if let Some(cache) = self.trigger_cache.triggers.get() {
            for t in cache {
                t.track();
            }
            return;
        }
        let mut triggers = Vec::new();
        if let Some(t) = self.triggers.get(&self.path) {
            t.this.track();
            triggers.push(t.this.clone());
            t.children.track();
            triggers.push(t.children.clone());
        }
        // `i = 0` covers the root path: the root's `children` channel is
        // the broadcast channel for root-level replacements (muon
        // collapses an all-Replace commit to a root Replace; raw writes
        // report the root). Every field reader subscribes it, so root
        // replacements reach field subscribers.
        for i in (0..self.path.len()).rev() {
            let ancestor: StorePath = self.path[..i].iter().cloned().collect();
            if let Some(t) = self.triggers.get(&ancestor) {
                t.children.track();
                triggers.push(t.children.clone());
            }
        }
        let _ = self.trigger_cache.triggers.set(triggers);
    }
}

impl<T: 'static, S: 'static> Clone for Field<T, S> {
    fn clone(&self) -> Self {
        Self {
            path: self.path.clone(),
            offset: self.offset,
            store: self.store.clone(),
            triggers: Arc::clone(&self.triggers),
            trigger_cache: Arc::clone(&self.trigger_cache),
            _phantom: PhantomData,
        }
    }
}
