//! The reactive layer: `ReactiveStore` (a plain store plus triggers),
//! the accessor bridge, and the `CommitNotify` extension.

use crate::path::{TriggerMap, TriggerSlot};
use muon::Observe;
use muon_store::{ChangeEvent, CommitResult, Store, StorePath};
use reactive_graph::traits::Notify;
use std::ops::Deref;
use std::sync::Arc;

/// A model type with reactive triggers registered.
///
/// Generated by `#[derive(Reactivity)]`. Supplies the trigger map used by
/// [`ReactiveStore`] for field-level subscription and notification.
pub trait Reactivity: Observe + Clone + 'static {
    /// Register a trigger pair for every field of `Self`.
    fn register_triggers(map: &mut TriggerMap);
}

/// Bridges field accessors onto [`ReactiveStore`] through `Deref`.
///
/// `#[derive(Reactivity)]` implements this trait and a per-type accessor
/// trait (`MuonTrack<Type>`); the `Deref` impl below exposes the
/// accessors as inherent-looking methods (`store.title()`) without any
/// trait import, while keeping the accessor traits local to the user's
/// crate (satisfying the orphan rules for `ReactiveStore<UserType>`).
#[doc(hidden)]
pub trait StoreFieldAccess: Sized + 'static {
    /// The per-type accessor trait object.
    type Target: ?Sized;
    /// Extract the accessor view from a reactive store.
    fn field_access(store: &ReactiveStore<Self>) -> &Self::Target;
}

/// A store with reactive triggers attached.
///
/// Composes a plain [`Store`] with a [`TriggerMap`]. The store half does
/// all the work (value, write path, change events); this type only adds
/// subscription and notification:
///
/// - [`notify`](ReactiveStore::notify) fires the triggers for a
///   [`ChangeEvent`] — call it *after* the write that produced the event
///   has returned, never while a store lock is held.
/// - `#[derive(Reactivity)]` generates field accessors on this type
///   (`store.title()`), each returning a [`Field`](crate::Field), reached
///   through `Deref` (no trait import needed).
///
/// Use [`core`](ReactiveStore::core) for the plain-store API
/// (`snapshot()`, `write`, `track!`): the deref target is the accessor
/// view, so `track!(store.core(), ...)` is the write entry point.
pub struct ReactiveStore<T: 'static> {
    core: Store<T>,
    triggers: Arc<TriggerMap>,
}

impl<T: 'static> ReactiveStore<T> {
    /// Create a reactive store, registering triggers for every field.
    ///
    /// Requires `T: Reactivity` (generated by `#[derive(Reactivity)]`),
    /// which supplies `register_triggers`.
    pub fn new(value: T) -> Self
    where
        T: Reactivity,
    {
        let mut triggers = TriggerMap::new();
        T::register_triggers(&mut triggers);
        Self {
            core: Store::new(value),
            triggers: Arc::new(triggers),
        }
    }

    /// The plain store underneath.
    pub fn core(&self) -> &Store<T> {
        &self.core
    }

    /// The trigger map attached to this store.
    #[doc(hidden)]
    pub fn triggers(&self) -> &Arc<TriggerMap> {
        &self.triggers
    }

    /// Fire the triggers for a change event's paths.
    ///
    /// Must be called after the producing write has released its lock —
    /// never while a store lock is held (an effect that writes back from
    /// its rerun would deadlock on the non-reentrant store lock).
    pub fn notify(&self, ev: &ChangeEvent) {
        let mut seen = rustc_hash::FxHashSet::default();
        for path in &ev.paths {
            if let Some(t) = self.triggers.get(path) {
                if seen.insert((path.clone(), TriggerSlot::This)) {
                    t.this.notify();
                }
                // A root-level mutation (muon collapses an all-Replace
                // commit to a root Replace; raw writes report the root)
                // changes every field's value. Fire the root's `children`
                // broadcast channel, which every field subscriber listens
                // on (see `Field::track`).
                if path.is_empty() && seen.insert((path.clone(), TriggerSlot::Children)) {
                    t.children.notify();
                }
            }
            for i in (1..path.len()).rev() {
                let ancestor: StorePath = path[..i].iter().cloned().collect();
                if let Some(t) = self.triggers.get(&ancestor)
                    && seen.insert((ancestor, TriggerSlot::Children))
                {
                    t.children.notify();
                }
            }
        }
    }
}

impl<T: 'static> Clone for ReactiveStore<T> {
    fn clone(&self) -> Self {
        Self {
            core: self.core.clone(),
            triggers: Arc::clone(&self.triggers),
        }
    }
}

impl<T: StoreFieldAccess + 'static> Deref for ReactiveStore<T> {
    type Target = T::Target;
    fn deref(&self) -> &Self::Target {
        T::field_access(self)
    }
}

/// Write + notify in one step.
///
/// Extension trait on [`CommitResult`]: after a write returns (the store
/// lock is released), notify the subscribers of a [`ReactiveStore`] and
/// yield the body's return value. The model type `T` is bound to the
/// result (`CommitResult<T, R>`), so a change event can only be notified
/// against a store of the same model type.
///
/// ```ignore
/// use muon_reactivity::CommitNotify;
/// track!(store.core(), |s| s.name = "x".into()).commit().notify(&store);
/// ```
pub trait CommitNotify<T> {
    /// The mutation body's return value.
    type Output;
    /// Notify the store's subscribers and return the body's result.
    fn notify(self, store: &ReactiveStore<T>) -> Self::Output;
}

impl<T, R> CommitNotify<T> for CommitResult<T, R> {
    type Output = R;
    fn notify(self, store: &ReactiveStore<T>) -> R {
        let (result, event) = self.into_parts();
        store.notify(&event);
        result
    }
}
